"""coding/ subdir support in the workflow loader.

Per-task coding workflows generated by the pipeline live under
`<workflows>/.build/coding/`. The loader must discover them
(`fetch_workflows`) and resolve them by their plain name
(`_load_workflow_record`), exactly like a flat top-level workflow.
"""

from __future__ import annotations

import asyncio
import json

import botcircuits.agent.workflow.local as wf_local


def _record(name: str) -> dict:
    return {
        "name": name,
        "description": f"test workflow {name}",
        "flow": {
            "start": "start",
            "variables": [],
            "steps": {
                "start": {"type": "start", "next": "s1"},
                "s1": {"type": "agentAction",
                       "settings": {"action": "do the thing"}},
            },
        },
    }


def _write_build(tmp_path, record: dict, *, subdir: str | None = None) -> None:
    build = tmp_path / ".build"
    if subdir:
        build = build / subdir
    build.mkdir(parents=True, exist_ok=True)
    (build / f"{record['name']}.json").write_text(json.dumps(record))


def test_fetch_discovers_coding_subdir(tmp_path, monkeypatch):
    monkeypatch.setenv(wf_local.WORKFLOWS_DIR_ENV, str(tmp_path))
    _write_build(tmp_path, _record("top_level_wf"))
    _write_build(tmp_path, _record("add_dark_mode_workflow"), subdir="coding")

    records = asyncio.run(wf_local.fetch_workflows())
    names = {r["name"] for r in records}
    assert "top_level_wf" in names
    assert "add_dark_mode_workflow" in names


def test_load_record_finds_coding_workflow_by_name(tmp_path, monkeypatch):
    monkeypatch.setenv(wf_local.WORKFLOWS_DIR_ENV, str(tmp_path))
    _write_build(tmp_path, _record("fix_parser_workflow"), subdir="coding")

    # Resolves by plain name even though the file is nested under coding/.
    record = wf_local._load_workflow_record("fix_parser_workflow")
    assert record["name"] == "fix_parser_workflow"


def test_top_level_shadows_none_when_only_coding(tmp_path, monkeypatch):
    monkeypatch.setenv(wf_local.WORKFLOWS_DIR_ENV, str(tmp_path))
    # No top-level build at all — only coding/. Discovery still works.
    _write_build(tmp_path, _record("only_coding_wf"), subdir="coding")
    records = asyncio.run(wf_local.fetch_workflows())
    assert [r["name"] for r in records] == ["only_coding_wf"]


def test_missing_workflow_still_errors(tmp_path, monkeypatch):
    monkeypatch.setenv(wf_local.WORKFLOWS_DIR_ENV, str(tmp_path))
    _write_build(tmp_path, _record("present_wf"), subdir="coding")
    try:
        wf_local._load_workflow_record("absent_wf")
    except wf_local.LocalWorkflowError:
        pass
    else:
        raise AssertionError("expected LocalWorkflowError for missing workflow")
